# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historico.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JanelaHistorico(object):
    def setupUi(self, JanelaHistorico):
        JanelaHistorico.setObjectName("JanelaHistorico")
        JanelaHistorico.resize(714, 480)
        JanelaHistorico.setMinimumSize(QtCore.QSize(714, 480))
        JanelaHistorico.setMaximumSize(QtCore.QSize(714, 480))
        self.centralwidget = QtWidgets.QWidget(JanelaHistorico)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 1, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("background-color: rgb(168, 168, 168);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lb_nome = QtWidgets.QLabel(self.frame)
        self.lb_nome.setGeometry(QtCore.QRect(100, 20, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lb_nome.setFont(font)
        self.lb_nome.setText("")
        self.lb_nome.setScaledContents(False)
        self.lb_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_nome.setObjectName("lb_nome")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.lw_entrada = QtWidgets.QListWidget(self.centralwidget)
        self.lw_entrada.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.lw_entrada.setFont(font)
        self.lw_entrada.setItemAlignment(QtCore.Qt.AlignCenter)
        self.lw_entrada.setObjectName("lw_entrada")
        self.gridLayout.addWidget(self.lw_entrada, 2, 0, 1, 1)
        JanelaHistorico.setCentralWidget(self.centralwidget)

        self.retranslateUi(JanelaHistorico)
        QtCore.QMetaObject.connectSlotsByName(JanelaHistorico)

    def retranslateUi(self, JanelaHistorico):
        _translate = QtCore.QCoreApplication.translate
        JanelaHistorico.setWindowTitle(_translate("JanelaHistorico", "HISTÓRICO DE MERCADORIA"))
