# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JanelaLogin(object):
    def setupUi(self, JanelaLogin):
        JanelaLogin.setObjectName("JanelaLogin")
        JanelaLogin.resize(323, 535)
        JanelaLogin.setMinimumSize(QtCore.QSize(323, 535))
        JanelaLogin.setMaximumSize(QtCore.QSize(323, 535))
        self.centralwidget = QtWidgets.QWidget(JanelaLogin)
        self.centralwidget.setMinimumSize(QtCore.QSize(323, 535))
        self.centralwidget.setMaximumSize(QtCore.QSize(323, 535))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setEnabled(True)
        self.top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top.setStyleSheet("background-color: rgb(173, 173, 173);")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fr_alert = QtWidgets.QFrame(self.top)
        self.fr_alert.setEnabled(True)
        self.fr_alert.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fr_alert.setStyleSheet("background-color: rgb(209, 31, 64);\n"
"border-radius: 20px;")
        self.fr_alert.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_alert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_alert.setObjectName("fr_alert")
        self.layoutWidget = QtWidgets.QWidget(self.fr_alert)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_erro = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lb_erro.setFont(font)
        self.lb_erro.setStyleSheet("")
        self.lb_erro.setText("")
        self.lb_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_erro.setObjectName("lb_erro")
        self.horizontalLayout_3.addWidget(self.lb_erro)
        self.btn_fechar_alert = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_fechar_alert.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_fechar_alert.setFont(font)
        self.btn_fechar_alert.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.btn_fechar_alert.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/x1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fechar_alert.setIcon(icon)
        self.btn_fechar_alert.setIconSize(QtCore.QSize(30, 30))
        self.btn_fechar_alert.setObjectName("btn_fechar_alert")
        self.horizontalLayout_3.addWidget(self.btn_fechar_alert)
        self.horizontalLayout.addWidget(self.fr_alert)
        self.verticalLayout.addWidget(self.top)
        self.middle = QtWidgets.QFrame(self.centralwidget)
        self.middle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle.setObjectName("middle")
        self.layoutWidget1 = QtWidgets.QWidget(self.middle)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 20, 202, 391))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_img = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_img.setMaximumSize(QtCore.QSize(200, 200))
        self.lb_img.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lb_img.setFont(font)
        self.lb_img.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_img.setText("")
        self.lb_img.setTextFormat(QtCore.Qt.AutoText)
        self.lb_img.setPixmap(QtGui.QPixmap("imgs/005-login-4.png"))
        self.lb_img.setScaledContents(True)
        self.lb_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_img.setIndent(-1)
        self.lb_img.setObjectName("lb_img")
        self.verticalLayout_3.addWidget(self.lb_img)
        self.le_login = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.le_login.setFont(font)
        self.le_login.setStyleSheet("QLineEdit {\n"
"    border: 2px solid;\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"}\n"
"")
        self.le_login.setInputMask("")
        self.le_login.setText("")
        self.le_login.setMaxLength(32767)
        self.le_login.setCursorPosition(0)
        self.le_login.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_login.setDragEnabled(False)
        self.le_login.setObjectName("le_login")
        self.verticalLayout_3.addWidget(self.le_login)
        self.le_senha = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.le_senha.setFont(font)
        self.le_senha.setStyleSheet("QLineEdit {\n"
"    border: 2px solid;\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"}\n"
"")
        self.le_senha.setText("")
        self.le_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_senha.setObjectName("le_senha")
        self.verticalLayout_3.addWidget(self.le_senha)
        self.btn_entrar = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_entrar.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_entrar.setFont(font)
        self.btn_entrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_entrar.setAutoFillBackground(False)
        self.btn_entrar.setStyleSheet("QPushButton {\n"
"    border: 2px solid;\n"
"    border-radius: 20px;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_entrar.setCheckable(False)
        self.btn_entrar.setAutoDefault(False)
        self.btn_entrar.setDefault(False)
        self.btn_entrar.setObjectName("btn_entrar")
        self.verticalLayout_3.addWidget(self.btn_entrar)
        self.verticalLayout.addWidget(self.middle)
        self.back = QtWidgets.QFrame(self.centralwidget)
        self.back.setMaximumSize(QtCore.QSize(16777215, 50))
        self.back.setStyleSheet("background-color: rgb(173, 173, 173);")
        self.back.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.back.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back.setObjectName("back")
        self.lb_contato = QtWidgets.QLabel(self.back)
        self.lb_contato.setGeometry(QtCore.QRect(130, 20, 201, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lb_contato.setFont(font)
        self.lb_contato.setObjectName("lb_contato")
        self.verticalLayout.addWidget(self.back)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        JanelaLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(JanelaLogin)
        QtCore.QMetaObject.connectSlotsByName(JanelaLogin)

    def retranslateUi(self, JanelaLogin):
        _translate = QtCore.QCoreApplication.translate
        JanelaLogin.setWindowTitle(_translate("JanelaLogin", "Login ERP 1.0 [Guilherme Silva]"))
        self.le_login.setPlaceholderText(_translate("JanelaLogin", "Login"))
        self.le_senha.setPlaceholderText(_translate("JanelaLogin", "Senha"))
        self.btn_entrar.setText(_translate("JanelaLogin", "ENTRAR"))
        self.lb_contato.setText(_translate("JanelaLogin", "contato: gusantos.ok@gmail.com"))
