# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saida.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JanelaSaida(object):
    def setupUi(self, JanelaSaida):
        JanelaSaida.setObjectName("JanelaSaida")
        JanelaSaida.resize(568, 487)
        JanelaSaida.setMinimumSize(QtCore.QSize(568, 487))
        JanelaSaida.setMaximumSize(QtCore.QSize(568, 487))
        JanelaSaida.setToolTipDuration(0)
        JanelaSaida.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(JanelaSaida)
        self.centralwidget.setMinimumSize(QtCore.QSize(568, 487))
        self.centralwidget.setObjectName("centralwidget")
        self.lw_entrada = QtWidgets.QListWidget(self.centralwidget)
        self.lw_entrada.setGeometry(QtCore.QRect(34, 12, 501, 271))
        self.lw_entrada.setStyleSheet("font: 75 12pt \"C059 [urw]\";")
        self.lw_entrada.setObjectName("lw_entrada")
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(389, 401, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_sair.setFont(font)
        self.btn_sair.setStyleSheet("")
        self.btn_sair.setObjectName("btn_sair")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(29, 331, 501, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 410, 309, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_entrada_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_entrada_id.setInputMask("")
        self.le_entrada_id.setText("")
        self.le_entrada_id.setMaxLength(9)
        self.le_entrada_id.setObjectName("le_entrada_id")
        self.horizontalLayout.addWidget(self.le_entrada_id)
        self.sb_entrada = QtWidgets.QSpinBox(self.layoutWidget)
        self.sb_entrada.setMaximum(999)
        self.sb_entrada.setObjectName("sb_entrada")
        self.horizontalLayout.addWidget(self.sb_entrada)
        self.lb_un = QtWidgets.QLabel(self.layoutWidget)
        self.lb_un.setStyleSheet("font: 75 12pt \"C059 [urw]\";")
        self.lb_un.setObjectName("lb_un")
        self.horizontalLayout.addWidget(self.lb_un)
        self.lb_mercadoria = QtWidgets.QLabel(self.centralwidget)
        self.lb_mercadoria.setGeometry(QtCore.QRect(40, 380, 153, 22))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_mercadoria.setFont(font)
        self.lb_mercadoria.setStyleSheet("")
        self.lb_mercadoria.setObjectName("lb_mercadoria")
        self.btn_log = QtWidgets.QToolButton(self.centralwidget)
        self.btn_log.setGeometry(QtCore.QRect(480, 290, 51, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_log.setIcon(icon)
        self.btn_log.setIconSize(QtCore.QSize(50, 50))
        self.btn_log.setObjectName("btn_log")
        JanelaSaida.setCentralWidget(self.centralwidget)

        self.retranslateUi(JanelaSaida)
        QtCore.QMetaObject.connectSlotsByName(JanelaSaida)

    def retranslateUi(self, JanelaSaida):
        _translate = QtCore.QCoreApplication.translate
        JanelaSaida.setWindowTitle(_translate("JanelaSaida", "SAÍDA DE MERCADORIA"))
        self.btn_sair.setText(_translate("JanelaSaida", "SAIR"))
        self.le_entrada_id.setToolTip(_translate("JanelaSaida", "<html><head/><body><p><br/></p></body></html>"))
        self.le_entrada_id.setWhatsThis(_translate("JanelaSaida", "<html><head/><body><p><br/></p></body></html>"))
        self.lb_un.setText(_translate("JanelaSaida", "UN"))
        self.lb_mercadoria.setText(_translate("JanelaSaida", "ID da mercadoria"))
        self.btn_log.setText(_translate("JanelaSaida", "..."))
